# Generated by Django 6.0 on 2025-12-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(help_text='Platform name (e.g., Shopee, Lazada)', max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='Base URL for the platform')),
                ('currency', models.CharField(default='MYR', help_text='Default currency code', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to scrape this platform')),
                ('scraping_delay', models.PositiveIntegerField(default=2, help_text='Delay between requests in seconds')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(help_text='Product name (e.g., iPhone 15 Pro)', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Product category (e.g., Electronics, Accessories)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('image_url', models.URLField(blank=True, help_text='Product image URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to track this product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('currency', models.CharField(default='MYR', help_text='Currency code (MYR, USD, etc.)', max_length=10)),
                ('product_url', models.URLField(help_text='Direct link to product page')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='When this price was scraped')),
                ('availability', models.CharField(blank=True, help_text='Stock status (In Stock, Out of Stock, etc.)', max_length=50)),
                ('seller_name', models.CharField(blank=True, help_text='Seller/shop name', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('platform', models.ForeignKey(help_text='E-commerce platform', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.platform')),
                ('product', models.ForeignKey(help_text='Product being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['product', 'platform', '-scraped_at'], name='products_pr_product_c1bf50_idx')],
            },
        ),
    ]
