# Generated by Django 6.0 on 2025-12-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL for the platform', null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='currency',
            field=models.CharField(blank=True, default='MYR', help_text='Default currency code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(blank=True, help_text='Platform name (e.g., Shopee, Lazada)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Product category (e.g., Electronics, Accessories)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Product name (e.g., iPhone 15 Pro)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product_url',
            field=models.URLField(blank=True, help_text='Direct link to product page', null=True),
        ),
    ]
