# Generated by Django 6.0 on 2025-12-05 07:27

import apps.products.models
import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_platform_base_url_alter_platform_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Suggestion Size: 600px * 600px', null=True, upload_to=apps.products.models._generate_product_image, verbose_name='Product Image'),
        ),
    ]
