# Generated by Django 6.0 on 2025-12-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto Generated', max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
