# Generated by Django 6.0 on 2025-12-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='availability',
            field=models.CharField(blank=True, help_text='Stock status (In Stock, Out of Stock, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='seller_name',
            field=models.CharField(blank=True, help_text='Seller/shop name', max_length=200, null=True),
        ),
    ]
