# Generated by Django 6.0 on 2025-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productprice_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='product_url',
            field=models.URLField(blank=True, help_text='Direct link to product page', max_length=2000, null=True),
        ),
    ]
